//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETPHIEUNHANPHONG
    {
        public int PHIEUNHANPHONG_ID { get; set; }
        public int KHACHHANG_ID { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual KHACHHANG KHACHHANG1 { get; set; }
        public virtual PHIEUNHANPHONG PHIEUNHANPHONG { get; set; }
        public virtual PHIEUNHANPHONG PHIEUNHANPHONG1 { get; set; }
    }
}
