//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETTRAPHONG
    {
        public int PHIEUTRAPHONG_ID { get; set; }
        public int DICHVU_ID { get; set; }
        public Nullable<int> SOLUONG { get; set; }
    
        public virtual DICHVU DICHVU { get; set; }
        public virtual PHIEUTRAPHONG PHIEUTRAPHONG { get; set; }
    }
}
