
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DTO
{

using System;
    using System.Collections.Generic;
    
public partial class DANHGIA
{

    public int ID { get; set; }

    public string NOIDUNG { get; set; }

    public Nullable<int> SOSAO { get; set; }

    public Nullable<int> PHIEUTRAPHONG_ID { get; set; }

    public Nullable<int> KHACHHANG_ID { get; set; }

    public Nullable<bool> ISDELETED { get; set; }



    public virtual KHACHHANG KHACHHANG { get; set; }

    public virtual PHIEUTRAPHONG PHIEUTRAPHONG { get; set; }

}

}
