
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DTO
{

using System;
    using System.Collections.Generic;
    
public partial class GIOHANG
{

    public int KHACHHANG_ID { get; set; }

    public int LOAIPHONG_ID { get; set; }

    public Nullable<int> SOLUONG { get; set; }

    public Nullable<double> DONGIA { get; set; }



    public virtual KHACHHANG KHACHHANG { get; set; }

    public virtual LOAIPHONG LOAIPHONG { get; set; }

}

}
