
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DTO
{

using System;
    using System.Collections.Generic;
    
public partial class PHIEUTRAPHONG
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public PHIEUTRAPHONG()
    {

        this.CHITIETTRAPHONGs = new HashSet<CHITIETTRAPHONG>();

        this.DANHGIAs = new HashSet<DANHGIA>();

    }


    public int ID { get; set; }

    public Nullable<System.DateTime> NGAYLAP { get; set; }

    public Nullable<decimal> TONGTIEN { get; set; }

    public Nullable<int> NHANVIEN_ID { get; set; }

    public Nullable<int> PHIEUNHANPHONG_ID { get; set; }

    public Nullable<decimal> TIENPHAT { get; set; }

    public string TINHTRANG { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CHITIETTRAPHONG> CHITIETTRAPHONGs { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DANHGIA> DANHGIAs { get; set; }

    public virtual NHANVIEN NHANVIEN { get; set; }

    public virtual PHIEUNHANPHONG PHIEUNHANPHONG { get; set; }

}

}
