//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUDATPHONG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEUDATPHONG()
        {
            this.PHIEUNHANPHONGs = new HashSet<PHIEUNHANPHONG>();
            this.KHACHHANGs = new HashSet<KHACHHANG>();
        }
    
        public int ID { get; set; }
        public Nullable<int> LOAIPHONG_ID { get; set; }
        public Nullable<System.DateTime> NGAYNHANPHONG { get; set; }
        public Nullable<System.DateTime> NGAYTRAPHONGDUKIEN { get; set; }
        public Nullable<decimal> THANHTOAN { get; set; }
        public string TINHTRANG { get; set; }
    
        public virtual LOAIPHONG LOAIPHONG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUNHANPHONG> PHIEUNHANPHONGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KHACHHANG> KHACHHANGs { get; set; }
    }
}
